
import React from 'react';
import { Artifact } from '../types';
import MermaidDiagram from './MermaidDiagram';

interface ArtifactPanelProps {
  artifacts: Artifact[];
  isOpen: boolean;
  onToggle: () => void;
  onPreview: (artifact: Artifact) => void;
}

const ArtifactPanel: React.FC<ArtifactPanelProps> = ({ artifacts, isOpen, onToggle, onPreview }) => {
  if (!isOpen) {
    return (
      <button 
        onClick={onToggle}
        className="absolute right-0 top-1/2 -translate-y-1/2 bg-gray-800 p-2 rounded-l-md border-l border-t border-b border-gray-700 hover:bg-gray-700 transition-colors z-20"
        title="Show Artifacts"
      >
        <i className="fa-solid fa-folder-open text-gray-400"></i>
      </button>
    );
  }

  return (
    <div className="w-80 lg:w-96 bg-gray-900 border-l border-gray-800 flex flex-col h-full flex-shrink-0 transition-all duration-300 relative">
      <div className="p-4 border-b border-gray-800 flex items-center justify-between bg-gray-900">
        <h2 className="text-sm font-bold text-gray-200 uppercase tracking-wider">Project Workspace</h2>
        <button onClick={onToggle} className="text-gray-500 hover:text-white transition-colors">
          <i className="fa-solid fa-xmark"></i>
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {artifacts.length === 0 ? (
          <div className="text-center mt-20 text-gray-600 flex flex-col items-center">
            <div className="w-16 h-16 rounded-full bg-gray-800/50 flex items-center justify-center mb-4">
                 <i className="fa-solid fa-layer-group text-2xl opacity-40"></i>
            </div>
            <p className="text-sm font-semibold text-gray-500">Awaiting Deliverables</p>
            <p className="text-xs mt-2 text-gray-600 max-w-[220px] leading-relaxed">
              Code snippets, architecture diagrams, and technical plans generated by the team will be filed here automatically.
            </p>
          </div>
        ) : (
          artifacts.map((artifact) => {
            const isPreviewable = ['html', 'tsx', 'jsx', 'javascript', 'js'].includes(artifact.language || '');
            const isMermaid = artifact.language === 'mermaid';
            
            return (
              <div key={artifact.id} className="bg-gray-950 rounded border border-gray-800 overflow-hidden shadow-sm hover:border-gray-700 transition-colors">
                <div className="bg-gray-900/50 px-3 py-2 border-b border-gray-800 flex items-center justify-between">
                  <span className="text-xs font-mono text-gray-400 truncate max-w-[150px]" title={artifact.title}>
                    {artifact.title}
                  </span>
                  <div className="flex items-center gap-2">
                      <span className="text-[10px] uppercase bg-gray-800 px-1.5 py-0.5 rounded text-gray-500">
                        {artifact.language || artifact.type}
                      </span>
                  </div>
                </div>

                <div className="p-3 overflow-x-auto relative group/code bg-gray-950">
                  {isMermaid ? (
                     <div className="bg-gray-900 rounded p-2 overflow-hidden">
                        <MermaidDiagram chart={artifact.content} />
                     </div>
                  ) : (
                    <>
                        <pre className="text-xs font-mono text-gray-300 whitespace-pre-wrap max-h-32 overflow-hidden mask-linear">
                            {artifact.content.length > 300 
                            ? artifact.content.substring(0, 300) + '...' 
                            : artifact.content}
                        </pre>
                        {isPreviewable && (
                            <div className="absolute inset-0 flex items-center justify-center bg-black/40 opacity-0 group-hover/code:opacity-100 transition-opacity">
                                <button 
                                    onClick={() => onPreview(artifact)}
                                    className="bg-green-600 hover:bg-green-500 text-white text-xs px-3 py-1.5 rounded shadow-lg transform translate-y-2 group-hover/code:translate-y-0 transition-all flex items-center gap-2"
                                >
                                    <i className="fa-solid fa-play"></i> Run Preview
                                </button>
                            </div>
                        )}
                    </>
                  )}
                </div>
                
                <div className="px-3 py-2 bg-gray-900/30 border-t border-gray-800 flex justify-between">
                   <button 
                    className="text-xs text-indigo-400 hover:text-indigo-300 flex items-center gap-1"
                    onClick={() => navigator.clipboard.writeText(artifact.content)}
                   >
                     <i className="fa-regular fa-copy"></i> Copy
                   </button>
                   {isPreviewable && (
                       <button 
                        className="text-xs text-green-400 hover:text-green-300 flex items-center gap-1 font-semibold"
                        onClick={() => onPreview(artifact)}
                       >
                         <i className="fa-solid fa-play"></i> Run
                       </button>
                   )}
                   {isMermaid && (
                       <span className="text-[10px] text-gray-500 flex items-center">
                           <i className="fa-solid fa-eye mr-1"></i> Visualized
                       </span>
                   )}
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};

export default ArtifactPanel;
